### ISSUE TITLE
Small updates

### ISSUE THREAD

**Issue by max-arnold** [aaronbassett/DisposableEmailChecker#4]
I have one candidate for deletion:

`bigmir.net`

This is Ukrainian web portal which also offers email service. It looks legit http://mail.bigmir.net/ and the registration form contains captcha, so I think this is not disposable http://passport.bigmir.net/registration/

Also there are two candidates to include:

```
reallymymail.com
putthisinyourspamdatabase.com
```

These are simply aliases for mailinator.com.

Also I suggest to remove duplicates from your list. This could be done with the following commands:

```
mv disposable_email_domains.txt{,.bak}
sed -e's/[[:space:]]*$//' disposable_email_domains.txt.bak | sort -u > disposable_email_domains.txt
rm disposable_email_domains.txt.bak
```

**Comment by aaronbassett** [comment]
Hey @max-arnold sorry for the _really_ late reply. I've made the recommended changes in a new rewrite branch (e8667efb1837b4f1821eb6bb6d0039602be28269), as well as fixed a lot of other issues including Python 3 support. However this rewrite does break backwards compatibility, but as it has been converted to a Django model field it should be easier to use. Of course there is a validator as well if you wish to use it directly.

 ```python
class MyModel(models.Model):
    email = DisposableEmailField()
```

I'm going to merge into master and push onto pypi asap.

**Comment by max-arnold** [comment]
Better late than never :)

Since my last post I found the most complete disposable email list (I also checked it for false positives I reported to you earlier and found none of them). I think you may find it useful as a primary data source: https://github.com/ivolo/disposable-email-domains/blob/master/index.json

**Comment by aaronbassett** [comment]
Thanks @max-arnold there is a new version (1.1.0) with the missing domains from the disposable-email-domains project added. I'll submit back to that project with the domains listed here which they don't have as well.
